services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: db_postgres
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    ports:
      - '54322:5432'
    volumes:
      - postgres_data:/bitnami/postgres

volumes:
  postgres_data:
    driver: local
